const FormFilds = [
  {
    label: "Name of the act",
    placeholder: "Select",
    fild: "legislation_",
    inputType: "select",
    options: [],
  },
  {
    label: "Rule/regulations",
    placeholder: "Select",
    fild: "rule_",
    inputType: "select",
    options: [],
  },
  {
    label: "ESG Category",
    placeholder: "Select ESG Category",
    fild: "esg_category",
    inputType: "select",
    options: ["Environment", "Social", "Governance"],
  },
  {
    label: "Law category",
    placeholder: "Select Law category",
    fild: "law_category",
    inputType: "select",
    options: [
      "Asset",
      "Corporate",
      "Securities",
      "Commercial",
      "EHS",
      "EXIM and FEMA",
      "Securities",
      "Human Resources",
      "Local",
      "Regulatory",
      "Finance",
      "Client Specific",
    ],
  },
  {
    label: "UID title",
    placeholder: "Enter",
    fild: "title",
    inputType: "text",
  },
  {
    label: "Reference (section, rule, etc)",
    placeholder: "Enter",
    fild: "reference",
    inputType: "text",
  },
  {
    label: "Applicability",
    placeholder: "Enter",
    fild: "applicability",
    inputType: "text",
  },

  {
    label: "Linkage",
    placeholder: "Enter Linkage",
    fild: "linkage",
    inputType: "select",
    options: ["parent", "child"],
  },
  {
    label: "compliance requirement",
    placeholder: "Enter",
    fild: "requirement",
    inputType: "text",
  },
  {
    label: "Numeric threshold",
    placeholder: "Enter",
    fild: "threshold",
    inputType: "text",
  },
  {
    label: "Threshold value",
    placeholder: "Enter",
    fild: "threshold_value",
    inputType: "text",
  },
  {
    label: "Unit of threshold",
    placeholder: "Enter",
    fild: "threshold_unit",
    inputType: "text",
  },
  {
    label: "Authority",
    placeholder: "Enter",
    fild: "authority",
    inputType: "text",
  },
  {
    label: "Frequency/periodicity",
    placeholder: "Select",
    fild: "frequency",
    inputType: "select",
    options: [
      "one time",
      "weekly",
      "monthly",
      "quarterly",
      "half yearly",
      "annually",
      "3 yearly",
      "5 yearly",
      "10 yearly",
      "event based",
      "ongoing",
    ],
  },
  {
    label: "Consequence of Non Compliance",
    placeholder: "Enter",
    fild: "consequenceOnCompliences",
    inputType: "text",
  },
  {
    label: "Amount of First Penalty or Range of First Penalty",
    placeholder: "Enter",
    fild: "first_penalty",
    inputType: "text",
  },

  {
    label: "Reference for Consequence of Non Compliance",
    placeholder: "Enter",
    fild: "reference",
    inputType: "text",
  },
  {
    label: "Corrective  Actions",
    placeholder: "Enter",
    fild: "corrective_actions",
    inputType: "text",
  },

  {
    label: "Severity",
    placeholder: "Enter",
    fild: "severity",
    inputType: "select",
    options: ["L1", "L2 a", "L2 b", "L4", "L5"],
  },
  {
    label: "Daily fine if applicable (yes/no)",
    placeholder: "Enter",
    fild: "daily_fine",
    inputType: "select",
    options: ["yes", "no"],
  },
  {
    label: "compoundable/ non compoundable ",
    placeholder: "Enter",
    fild: "is_compoundable",
    inputType: "select",
    options: ["compoundable", "non compoundable"],
  },
  {
    label: "Help Text",
    placeholder: "Enter",
    fild: "help_text",
    inputType: "text",
  },
  {
    label: "Online Link",
    placeholder: "Enter",
    fild: "online_link",
    inputType: "text",
  },

  {
    label: "Form Name and Number",
    placeholder: "Enter",
    fild: "form_details",
    inputType: "text",
  },
  {
    label: "Source Matrix",
    placeholder: "Enter",
    fild: "source_matrix",
    inputType: "text",
  },
  {
    label: "Update Page crawler Link",
    placeholder: "Enter",
    fild: "update_page_crawler_link",
    inputType: "text",
  },
  //   {
  //     label: "Date till the updates are captured",
  //     placeholder: "Enter",
  //     fild: "penaltyAmount",
  //     inputType: "text",
  //   },
  //   {
  //     label: "Time of the last update check",
  //     placeholder: "Enter",
  //     fild: "penaltyAmount",
  //     inputType: "text",
  //   },
  //   {
  //     label: "Event Question",
  //     placeholder: "Enter",
  //     fild: "penaltyAmount",
  //     inputType: "text",
  //   },
  //   {
  //     label: "Global Principles",
  //     placeholder: "Enter",
  //     fild: "penaltyAmount",
  //     inputType: "text",
  //   },
];

export default FormFilds;
