import { lazy } from "react";

const PagesRoutes = [
  {
    path: "/dashboard",
    id: "/dashboard",
    title: <div>Dashboard</div>,
    component: lazy(() => import("../../view/main/dashboard/analytics")),
    layout: "VerticalLayout",
    role: "SUPER_ADMIN",
  },
  {
    path: "/organizations",
    id: "/organizations",
    title: <div>Organizations</div>,
    component: lazy(() => import("../../view/pages/errors/coming-soon")),
    layout: "VerticalLayout",
    role: "SUPER_ADMIN",
  },
  {
    path: "/central-repository",
    id: "/central-repository",
    title: <div>Central repository</div>,
    component: lazy(() => import("../../view/main/centralRepo")),
    layout: "VerticalLayout",
    role: "SUPER_ADMIN",
  },
  {
    path: "/view-central-repository",
    id: "/view-central-respository",
    title: <div></div>,
    component: lazy(() =>
      import("../../view/main/centralRepo/components/Repotable")
    ),
    layout: "VerticalLayout",
    role: "SUPER_ADMIN",
  },
  {
    path: "/parent-child-tagging/:id",
    id: "/parent-child-tagging/0",
    title: <div>Parent child tagging</div>,
    component: lazy(() => import("../../view/main/parentChildTagging")),
    layout: "VerticalLayout",
    role: "SUPER_ADMIN",
  },
  {
    path: "/assign-compliances",
    id: "/assign-compliances",
    title: <div>Assign compliances</div>,
    component: lazy(() => import("../../view/main/assignCompliances")),
    layout: "VerticalLayout",
    role: "SUPER_ADMIN",
  },
  {
    path: "/utility",
    id: "/utility",
    title: <div>Utility</div>,
    component: lazy(() => import("../../view/main/utility")),
    layout: "VerticalLayout",
    role: "SUPER_ADMIN",
  },

  {
    path: "/apps/calendar",
    id: "/app-calendar",
    title: <div></div>,
    component: lazy(() => import("../../view/apps/calendar")),
    layout: "VerticalLayout",
    role: "SUPER_ADMIN",
  },
  {
    path: "/additional-services",
    id: "/additional-services",
    title: <div>Additional services</div>,
    component: lazy(() => import("../../view/pages/errors/coming-soon")),
    layout: "VerticalLayout",
    role: "SUPER_ADMIN",
  },
  {
    path: "/master",
    id: "/master",
    title: <div>Master</div>,
    component: lazy(() => import("../../view/main/master/")),
    layout: "VerticalLayout",
    role: "SUPER_ADMIN",
  },
  {
    path: "/onboarding",
    id: "/onboarding",
    title: <div>Onboarding</div>,
    component: lazy(() => import("../../view/main/onboarding/")),
    layout: "VerticalLayout",
    role: "SUPER_ADMIN",
  },
  {
    path: "/onboarding-unit",
    id: "/onboarding-unit",
    title: <div>Onboarding</div>,
    component: lazy(() => import("../../view/main/onboardingUnit/")),
    layout: "VerticalLayout",
    role: "ENTITY_ADMIN",
  },
  {
    path: "/compliance-repository",
    id: "/compliance-repository",
    title: <div>Compliance Repository</div>,
    component: lazy(() => import("../../view/main/complianceRepository/")),
    layout: "VerticalLayout",
    role: "ENTITY_ADMIN",
  },
  {
    path: "/compliance-repository",
    id: "/compliance-repository",
    title: <div>Compliance Repository</div>,
    component: lazy(() => import("../../view/main/complianceRepository/")),
    layout: "VerticalLayout",
    role: "L1",
  },
  {
    path: "/user-compliance-repository",
    id: "/user-compliance-repository",
    title: <div>Compliance Repository</div>,
    component: lazy(() => import("../../view/main/complianceRepositoryUser/")),
    layout: "VerticalLayout",
    role: "L1",
  },
];

export default PagesRoutes;
