const FormFilds = [
  // { label: "UID", placeholder: "Enter UID", fild: "uid", inputType: "text" },
  {
    label: "Name of the act",
    placeholder: "Select",
    fild: "legislation",
    inputType: "select",
    options: ["a", "b", "c"],
  },
  {
    label: "Rule/regulations",
    placeholder: "Select",
    fild: "ruleRegulations",
    inputType: "select",
    options: ["a", "b", "c"],
  },
  {
    label: "Law category",
    placeholder: "Select Law category",
    fild: "lowCategory",
    inputType: "select",
    options: ["a", "b", "c"],
  },
  {
    label: "ESG Category",
    placeholder: "Select ESG Category",
    fild: "esgCategory",
    inputType: "select",
    options: ["a", "b", "c"],
  },
  {
    label: "Central/state/UT",
    placeholder: "Select type",
    fild: "centralState",
    inputType: "select",
    options: ["a", "b", "c"],
  },
  {
    label: "Name of state",
    placeholder: "Select state",
    fild: "stateName",
    inputType: "select",
    options: ["a", "b", "c"],
  },
  {
    label: "Linkage",
    placeholder: "Enter Linkage",
    fild: "linkage",
    inputType: "text",
  },
  {
    label: "Reference (section, rule, etc)",
    placeholder: "Enter",
    fild: "reference",
    inputType: "text",
  },
  {
    label: "Applicability",
    placeholder: "Enter",
    fild: "applicability",
    inputType: "text",
  },
  {
    label: "UID title",
    placeholder: "Enter",
    fild: "UIDTitle",
    inputType: "text",
  },
  {
    label: "compliance requirement",
    placeholder: "Enter",
    fild: "complianceRequirement",
    inputType: "text",
  },
  {
    label: "Numeric threshold",
    placeholder: "Enter",
    fild: "numericThreshold",
    inputType: "text",
  },
  {
    label: "Unit of threshold",
    placeholder: "Enter",
    fild: "thresholdUnit",
    inputType: "text",
  },
  {
    label: "Authority",
    placeholder: "Enter",
    fild: "authority",
    inputType: "text",
  },
  {
    label: "Frequency/periodicity",
    placeholder: "Select",
    fild: "frequencyPeriodicity",
    inputType: "select",
    options: ["a", "b", "c"],
  },
  {
    label: "Consequence of Non Compliance",
    placeholder: "Enter",
    fild: "consequenceOfNonCompliance",
    inputType: "text",
  },
  {
    label: "Corrective  Actions",
    placeholder: "Enter",
    fild: "correctiveActions",
    inputType: "text",
  },
  {
    label: "Amount of First Penalty or Range of First Penalty",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
  {
    label: "Reference for Consequence of Non Compliance",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
  {
    label: "Severity",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "select",
    options: ["a", "b", "c"],
  },
  {
    label: "Daily fine if applicable (yes/no)",
    placeholder: "Enter",
    fild: "correctiveActions",
    inputType: "text",
  },
  {
    label: "Daily fine if applicable (amount)",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
  {
    label: "Online Link",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
  {
    label: "Help Text",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
  {
    label: "Compoundable/Non Compoundable ",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "select",
    options: ["a", "b", "c"],
  },
  {
    label: "Form Name and Number",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
  {
    label: "Source Matrix",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
  {
    label: "Update Page crawler Link",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
  {
    label: "Date till the updates are captured",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
  {
    label: "Time of the last update check",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
  {
    label: "Event Question",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
  {
    label: "Global Principles",
    placeholder: "Enter",
    fild: "penaltyAmount",
    inputType: "text",
  },
];

export default FormFilds;
