const FormFilds = [
  { label: "UID", placeholder: "Enter UID", fild: "UID", inputType: "text" },
  {
    label: "Name of Legislation",
    placeholder: "Enter Name of Legislation",
    fild: "name",
    inputType: "text",
  },
  {
    label: "Rule",
    placeholder: "Enter Rule",
    fild: "rule_name",
    inputType: "text",
  },
  {
    label: "Law Category",
    placeholder: "Enter Law Category",
    fild: "law_category",
    inputType: "text",
  },
  {
    label: "ESG Category",
    placeholder: "Enter ESG Category",
    fild: "esg_category",
    inputType: "text",
  },
  {
    label: "CSU Category",
    placeholder: "Enter CSU Category",
    fild: "csu_category",
    inputType: "text",
  },
  {
    label: "Name of State",
    placeholder: "Enter Name of State",
    fild: "name_of_state",
    inputType: "text",
  },
  {
    label: "Linkage",
    placeholder: "Enter Linkage",
    fild: "linkage",
    inputType: "text",
  },
  {
    label: "Reference",
    placeholder: "Enter Reference",
    fild: "reference",
    inputType: "text",
  },
  {
    label: "Applicability",
    placeholder: "Enter Applicability",
    fild: "applicability",
    inputType: "text",
  },
  {
    label: "Title",
    placeholder: "Enter Title",
    fild: "title",
    inputType: "text",
  },
  {
    label: "Requirement",
    placeholder: "Enter Requirement",
    fild: "requirement",
    inputType: "text",
  },
  {
    label: "Threshold",
    placeholder: "Enter Threshold",
    fild: "threshold",
    inputType: "text",
  },
  {
    label: "Threshold Value",
    placeholder: "Enter Threshold Value",
    fild: "threshold_value",
    inputType: "number",
  },
  {
    label: "Threshold Unit",
    placeholder: "Enter Threshold Unit",
    fild: "threshold_unit",
    inputType: "text",
  },
  {
    label: "Authority",
    placeholder: "Enter Authority",
    fild: "authority",
    inputType: "text",
  },
  {
    label: "Frequency",
    placeholder: "Enter Frequency",
    fild: "frequency",
    inputType: "text",
  },
  {
    label: "Consequence",
    placeholder: "Enter Consequence",
    fild: "consequence",
    inputType: "text",
  },
  {
    label: "First Penalty",
    placeholder: "Enter First Penalty",
    fild: "first_penalty",
    inputType: "text",
  },
  {
    label: "Reference for Consequence",
    placeholder: "Enter Reference for Consequence",
    fild: "consequence_reference",
    inputType: "text",
  },
  {
    label: "Corrective Actions",
    placeholder: "Enter Corrective Actions",
    fild: "corrective_actions",
    inputType: "text",
  },
  {
    label: "Severity",
    placeholder: "Enter Severity",
    fild: "severity",
    inputType: "text",
  },
  {
    label: "Daily Fine",
    placeholder: "Select Daily Fine",
    fild: "daily_fine",
    inputType: "select",
    options: ["Yes", "No"],
  },
  {
    label: "Daily Fine Amount",
    placeholder: "Enter Daily Fine Amount",
    fild: "daily_fine_amount",
    inputType: "text",
  },
  {
    label: "Is Compoundable",
    placeholder: "Select Is Compoundable",
    fild: "is_compoundable",
    inputType: "select",
    options: ["Compoundable", "Non-Compoundable"],
  },
  {
    label: "Help Text",
    placeholder: "Enter Help Text",
    fild: "help_text",
    inputType: "text",
  },
  {
    label: "Form Details",
    placeholder: "Enter Form Details",
    fild: "form_details",
    inputType: "text",
  },
  {
    label: "Online Link",
    placeholder: "Enter Online Link",
    fild: "online_link",
    inputType: "text",
  },
  {
    label: "Source Matrix",
    placeholder: "Enter Source Matrix",
    fild: "source_matrix",
    inputType: "text",
  },
  {
    label: "Update Page Crawler Link",
    placeholder: "Enter Update Page Crawler Link",
    fild: "update_page_crawler_link",
    inputType: "text",
  },
  {
    label: "Event Question",
    placeholder: "Enter Event Question",
    fild: "event_question",
    inputType: "text",
  },
  {
    label: "Global Principles",
    placeholder: "Enter Global Principles",
    fild: "global_principles",
    inputType: "text",
  },

  // { label: "UID", placeholder: "Enter UID", fild: "uid", inputType: "text" },
  // {
  //   label: "ESG Category",
  //   placeholder: "Select ESG Category",
  //   fild: "esgCategory",
  //   inputType: "select",
  //   options: ["a", "b", "c"],
  // },
  // {
  //   label: "Law category",
  //   placeholder: "Select Law category",
  //   fild: "lowCategory",
  //   inputType: "select",
  //   options: ["a", "b", "c"],
  // },
  // {
  //   label: "Central/state/UT",
  //   placeholder: "Select type",
  //   fild: "centralState",
  //   inputType: "select",
  //   options: ["a", "b", "c"],
  // },
  // {
  //   label: "Name of state",
  //   placeholder: "Select state",
  //   fild: "stateName",
  //   inputType: "select",
  //   options: ["a", "b", "c"],
  // },
  // {
  //   label: "Name of the act",
  //   placeholder: "Select",
  //   fild: "actName",
  //   inputType: "select",
  //   options: ["a", "b", "c"],
  // },
  // {
  //   label: "Rule/regulations",
  //   placeholder: "Select",
  //   fild: "ruleRegulations",
  //   inputType: "select",
  //   options: ["a", "b", "c"],
  // },
  // {
  //   label: "Linkage",
  //   placeholder: "Enter Linkage",
  //   fild: "linkage",
  //   inputType: "text",
  // },
  // {
  //   label: "Reference (section, rule, etc)",
  //   placeholder: "Enter",
  //   fild: "reference",
  //   inputType: "text",
  // },
  // {
  //   label: "Applicability",
  //   placeholder: "Enter",
  //   fild: "applicability",
  //   inputType: "text",
  // },
  // {
  //   label: "UID title",
  //   placeholder: "Enter",
  //   fild: "UIDTitle",
  //   inputType: "text",
  // },
  // {
  //   label: "compliance requirement",
  //   placeholder: "Enter",
  //   fild: "complianceRequirement",
  //   inputType: "text",
  // },
  // {
  //   label: "Numeric threshold",
  //   placeholder: "Enter",
  //   fild: "numericThreshold",
  //   inputType: "text",
  // },
  // {
  //   label: "Unit of threshold",
  //   placeholder: "Enter",
  //   fild: "thresholdUnit",
  //   inputType: "text",
  // },
  // {
  //   label: "Authority",
  //   placeholder: "Enter",
  //   fild: "authority",
  //   inputType: "text",
  // },
  // {
  //   label: "Frequency/periodicity",
  //   placeholder: "Select",
  //   fild: "frequencyPeriodicity",
  //   inputType: "select",
  //   options: ["a", "b", "c"],
  // },
  // {
  //   label: "Consequence of Non Compliance",
  //   placeholder: "Enter",
  //   fild: "consequenceOfNonCompliance",
  //   inputType: "text",
  // },
  // {
  //   label: "Corrective  Actions",
  //   placeholder: "Enter",
  //   fild: "correctiveActions",
  //   inputType: "text",
  // },
  // {
  //   label: "Amount of First Penalty or Range of First Penalty",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
  // {
  //   label: "Reference for Consequence of Non Compliance",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
  // {
  //   label: "Severity",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "select",
  //   options: ["a", "b", "c"],
  // },
  // {
  //   label: "Daily fine if applicable (yes/no)",
  //   placeholder: "Enter",
  //   fild: "correctiveActions",
  //   inputType: "text",
  // },
  // {
  //   label: "Daily fine if applicable (amount)",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
  // {
  //   label: "Online Link",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
  // {
  //   label: "Help Text",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
  // {
  //   label: "Compoundable/Non Compoundable ",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "select",
  //   options: ["a", "b", "c"],
  // },
  // {
  //   label: "Form Name and Number",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
  // {
  //   label: "Source Matrix",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
  // {
  //   label: "Update Page crawler Link",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
  // {
  //   label: "Date till the updates are captured",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
  // {
  //   label: "Time of the last update check",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
  // {
  //   label: "Event Question",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
  // {
  //   label: "Global Principles",
  //   placeholder: "Enter",
  //   fild: "penaltyAmount",
  //   inputType: "text",
  // },
];

export default FormFilds;
